package ule.edi.model;
// Generated 30-may-2021 21:09:22 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inventariohospital generated by hbm2java
 */
public class Inventariohospital  implements java.io.Serializable {


     private int id;
     private Date fecha;
     private String tipoSangre;
     private String nombreDuenyo;

    public Inventariohospital() {
    }

	
    public Inventariohospital(int id, String tipoSangre, String nombreDuenyo) {
        this.id = id;
        this.tipoSangre = tipoSangre;
        this.nombreDuenyo = nombreDuenyo;
    }
    public Inventariohospital(int id, Date fecha, String tipoSangre, String nombreDuenyo) {
       this.id = id;
       this.fecha = fecha;
       this.tipoSangre = tipoSangre;
       this.nombreDuenyo = nombreDuenyo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public String getNombreDuenyo() {
        return this.nombreDuenyo;
    }
    
    public void setNombreDuenyo(String nombreDuenyo) {
        this.nombreDuenyo = nombreDuenyo;
    }




}


