package ule.edi.model;
// Generated 18-jun-2021 23:36:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inventariohospital generated by hbm2java
 */
public class Inventariohospital  implements java.io.Serializable {


     private Integer id;
     private Date fecha;
     private String tipoSangre;
     private String nombreDuenyo;

    public Inventariohospital() {
    }

	
    public Inventariohospital(String tipoSangre, String nombreDuenyo) {
        this.tipoSangre = tipoSangre;
        this.nombreDuenyo = nombreDuenyo;
    }
    public Inventariohospital(Date fecha, String tipoSangre, String nombreDuenyo) {
       this.fecha = fecha;
       this.tipoSangre = tipoSangre;
       this.nombreDuenyo = nombreDuenyo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public String getNombreDuenyo() {
        return this.nombreDuenyo;
    }
    
    public void setNombreDuenyo(String nombreDuenyo) {
        this.nombreDuenyo = nombreDuenyo;
    }




}


