package ule.edi.model;
// Generated 18-jun-2021 23:36:29 by Hibernate Tools 4.3.1


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Inventariohospital generated by hbm2java
 */
public class Inventariohospital  implements java.io.Serializable {


     private Integer id;
     private Date fecha;
     private String tipoSangre;
     private String nombreDuenyo;

    public Inventariohospital() {
    }

	
    public Inventariohospital(String tipoSangre, String nombreDuenyo) {
        this.tipoSangre = tipoSangre;
        this.nombreDuenyo = nombreDuenyo;
    }
    public Inventariohospital(Date fecha, String tipoSangre, String nombreDuenyo) {
       this.fecha = fecha;
       this.tipoSangre = tipoSangre;
       this.nombreDuenyo = nombreDuenyo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
         String a="";
        a=fecha.toString();
         Date date1 = new Date();
         try {  
              date1=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").parse(a);
         } catch (ParseException ex) {
             Logger.getLogger(ule.edi.beans.Pedidoshechos.class.getName()).log(Level.SEVERE, null, ex);
         }
        return date1;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public String getNombreDuenyo() {
        return this.nombreDuenyo;
    }
    
    public void setNombreDuenyo(String nombreDuenyo) {
        this.nombreDuenyo = nombreDuenyo;
    }




}


