package ule.edi.model;
// Generated 18-jun-2021 23:36:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer id;
     private Date fecha;
     private String tipo;
     private int dosis;
     private String usuarioDestino;

    public Pedidos() {
    }

	
    public Pedidos(String tipo, int dosis, String usuarioDestino) {
        this.tipo = tipo;
        this.dosis = dosis;
        this.usuarioDestino = usuarioDestino;
    }
    public Pedidos(Date fecha, String tipo, int dosis, String usuarioDestino) {
       this.fecha = fecha;
       this.tipo = tipo;
       this.dosis = dosis;
       this.usuarioDestino = usuarioDestino;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getDosis() {
        return this.dosis;
    }
    
    public void setDosis(int dosis) {
        this.dosis = dosis;
    }
    public String getUsuarioDestino() {
        return this.usuarioDestino;
    }
    
    public void setUsuarioDestino(String usuarioDestino) {
        this.usuarioDestino = usuarioDestino;
    }




}


